### ISSUE TITLE
Dark Image Issue with ScanNet 3D Scenes When Generating Image Pairs

### ISSUE THREAD

**Issue by turhancan97** [naver/croco#31]
Hello,

I want to reproduce your experiments. I've been generating image pairs using the metadata provided for ScanNet 3D scenes. While generating pairs from other datasets like HM3D and Replica works fine, the images generated from ScanNet are extremely dark, as shown below:

![00000000_1](https://github.com/user-attachments/assets/d0a09e86-ef19-4f22-af95-1a305c3a1349) ![00000000_2](https://github.com/user-attachments/assets/d6c5e646-928a-45af-ac94-05b47a3a80da)

I used the same code from your repository for all datasets. The metadata-based generation worked correctly for other scenes, but ScanNet outputs seem to have lighting issues. Did you pretrained CroCo also with dark images from ScanNet, or I should fix this issue before pretaining. 

Thank you in advance for your assistance!

**Comment by rbregier** [comment]
Hi,
The ScanNet images I checked looked fine, for example:
![image](https://github.com/user-attachments/assets/c1d2624d-75e3-47ab-b756-7cd2af42314c)
![image](https://github.com/user-attachments/assets/3475e4e3-e942-449e-9d51-bd84328c9066)

Your issue may be due to a conversion problem from the ScanNet dataset to the format expected by Habitat-Sim, but this is a rather wild guess.

**Comment by turhancan97** [comment]
I tried different method to convert ScanNet format (*.ply) to expected format (*.glb). Now, it works. Thanks for the answer :)
