### ISSUE TITLE
The result

### ISSUE THREAD

**Issue by syliu123** [naver/croco#4]
I have a question to ask. In the paper, the D1-all value for KITTI 2015 is 2.03. However, in the KITTI 2015 stereo benchmark, the D1-all value is 1.59. Was this improvement achieved by adjusting parameters or implementing other effective methods?

**Comment by PhilippeWeinzaepfel** [comment]
Hi,

In the ICCV'23 camera-ready version (which corresponds to version v3 on arxiv) we indeed report 1.59 D1-all, as you see in the official kitti 15 leaderboard.
The 2.03 D1-all you mentioned was from the version v2 of arxiv from March 2023. 
The main difference between the two versions is that we finetune on higher-resolution crops (1216x352) instead of 704x352. There are also some minor differences that should have low impact, i.e. we bound the confidence in the loss, etc.

Best
Philippe

**Comment by syliu123** [comment]
Thanks for your response!
